print('hey')
print("2*3, hey there")
print("2*3", "hey there")
print('1' + 'hello')
print('1' + ' ' + 'hello')
print('1'+' hello')
print('1', 'hello')
print('1 hello')
print(1,2,12,  13)
print('1 2 12 13')
print(2,'one')
print(2+4)
print()
print('hey', 'this is', 'deeps')
print('hey "this is" deeps')
print("hey 'this is' deeps")
print("hey \'deeps\' how are u today")
print('hey deeps how are u today')
print(2*2, "is = " "4")
print("hello USA")
print("hello USA\nthis is Deeps")